### ISSUE TITLE
Writing to file will error out

### ISSUE THREAD

**Issue by beornling** [TheGuardianWolf/concat-licenses#4]
When running "npx concat-licenses LICENSE.lib.txt", I get this error:

> ERROR: Writing to file requires exactly one parameter!

When looking at the code, shouldn't bin/concat-licenses actual check for argv._.length > 1 instead of >= 1?

**Comment by sourcevault** [comment]
`concat-licenses --allowGuess > ./LICENCE.min.txt`

for now, until it's fixed.

**Comment by TheGuardianWolf** [comment]
I should probably get to this

**Comment by TheGuardianWolf** [comment]
Done

**Comment by sourcevault** [comment]
![publish](https://user-images.githubusercontent.com/20347647/102315869-15060c80-3f9f-11eb-85cd-db1185b440b9.png)

Thank you ! 有り難う ! 😊
